In [82]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [83]:
df = pd.read_excel('train_final_database.xlsx')

In [84]:
df.head()

shopping_pt  group_size  homeowner  car_age  risk_factor  age_oldest  \
0            9           2          0        2            3          46   
1            6           1          0       10            4          28   
2            8           1          0       11            5          43   
3            4           2          1        3            3          62   
4            6           1          0        5            3          32   

   age_youngest  married_couple  C_previous  duration_previous     ...      \
0            42               1           1                  2     ...       
1            28               0           3                 13     ...       
2            43               0           2                  4     ...       
3            60               1           3                  3     ...       
4            28               1           1                  2     ...       

   time3  time4  car_valueA  car_valueB  car_valueC  car_valueD  car_valueE  \
0      1      0           0           0           0           0           0   
1      0      0           0           0           0           0           1   
2      1      0           0           0           1           0           0   
3      0      0           0           0           0           1           0   
4      0      1           0           0           0           1           0   

   car_valueF  car_valueG  car_valueH  
0           0           1           0  
1           0           0           0  
2           0           0           0  
3           0           0           0  
4           0           0           0  

[5 rows x 72 columns]

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97009 entries, 0 to 97008
Data columns (total 72 columns):
shopping_pt          97009 non-null int64
group_size           97009 non-null int64
homeowner            97009 non-null int64
car_age              97009 non-null int64
risk_factor          97009 non-null int64
age_oldest           97009 non-null int64
age_youngest         97009 non-null int64
married_couple       97009 non-null int64
C_previous           97009 non-null int64
duration_previous    97009 non-null int64
first_insurance      97009 non-null int64
cost                 97009 non-null int64
A                    97009 non-null int64
B                    97009 non-null int64
C                    97009 non-null int64
D                    97009 non-null int64
E                    97009 non-null int64
F                    97009 non-null int64
G                    97009 non-null int64
AL                   97009 non-null int64
AR                   97009 non-null int64
CO       

In [86]:
df.describe()

shopping_pt    group_size     homeowner       car_age   risk_factor  \
count  97009.000000  97009.000000  97009.000000  97009.000000  97009.000000   
mean       6.857601      1.235617      0.545485      8.181066      3.425187   
std        1.998357      0.461796      0.497929      5.796504      1.471005   
min        3.000000      1.000000      0.000000      0.000000      1.000000   
25%        5.000000      1.000000      0.000000      3.000000      2.000000   
50%        7.000000      1.000000      1.000000      8.000000      4.000000   
75%        8.000000      1.000000      1.000000     12.000000      5.000000   
max       13.000000      4.000000      1.000000     85.000000      5.000000   

         age_oldest  age_youngest  married_couple    C_previous  \
count  97009.000000  97009.000000    97009.000000  97009.000000   
mean      45.181622     42.682545        0.211692      2.432836   
std       17.389647     17.488953        0.408510      1.053662   
min       18.000000     16.000000        0.000000      0.000000   
25%       29.000000     26.000000        0.000000      1.000000   
50%       44.000000     40.000000        0.000000      3.000000   
75%       60.000000     57.000000        0.000000      3.000000   
max       75.000000     75.000000        1.000000      4.000000   

       duration_previous      ...              time3         time4  \
count       97009.000000      ...       97009.000000  97009.000000   
mean            6.040254      ...           0.514055      0.168304   
std             4.712596      ...           0.499805      0.374138   
min             0.000000      ...           0.000000      0.000000   
25%             2.000000      ...           0.000000      0.000000   
50%             5.000000      ...           1.000000      0.000000   
75%             9.000000      ...           1.000000      0.000000   
max            15.000000      ...           1.000000      1.000000   

         car_valueA    car_valueB    car_valueC    car_valueD    car_valueE  \
count  97009.000000  97009.000000  97009.000000  97009.000000  97009.000000   
mean       0.001794      0.002165      0.031667      0.169077      0.331526   
std        0.042314      0.046477      0.175113      0.374822      0.470764   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      1.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

         car_valueF    car_valueG    car_valueH  
count  97009.000000  97009.000000  97009.000000  
mean       0.267429      0.148306      0.042862  
std        0.442620      0.355405      0.202547  
min        0.000000      0.000000      0.000000  
25%        0.000000      0.000000      0.000000  
50%        0.000000      0.000000      0.000000  
75%        1.000000      0.000000      0.000000  
max        1.000000      1.000000      1.000000  

[8 rows x 72 columns]

### Logistic Regression

In [87]:
columns = 'shopping_pt	group_size	homeowner	car_age	risk_factor	age_oldest	age_youngest	married_couple	C_previous	duration_previous	first_insurance	cost	A	B	C	D	E	F	G	AL	AR	CO	CT	DC	DE	FL	GA	IA	ID	IN	KS	KY	MD	ME	MO	MS	MT	ND	NE	NH	NM	NV	NY	OH	OK	OR	PA	RI	SD	TN	UT	WA	WI	WV	Mon	Tues	Wed	Thur	Fri	Sat	time1 time2	time3	time4	car_valueA	car_valueB	car_valueC	car_valueD	car_valueE	car_valueF	car_valueG	car_valueH'
columns = columns.split()
columns[:5]

['shopping_pt', 'group_size', 'homeowner', 'car_age', 'risk_factor']

** Split the data into training set and testing set using train_test_split**
### Test 'A' alone

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
X = df[columns]
X.drop('A',axis=1,inplace=True)
X.drop('B',axis=1,inplace=True)
X.drop('C',axis=1,inplace=True)
X.drop('D',axis=1,inplace=True)
X.drop('E',axis=1,inplace=True)
X.drop('F',axis=1,inplace=True)
X.drop('G',axis=1,inplace=True)
y = df['A']
X.head()

shopping_pt  group_size  homeowner  car_age  risk_factor  age_oldest  \
0            9           2          0        2            3          46   
1            6           1          0       10            4          28   
2            8           1          0       11            5          43   
3            4           2          1        3            3          62   
4            6           1          0        5            3          32   

   age_youngest  married_couple  C_previous  duration_previous     ...      \
0            42               1           1                  2     ...       
1            28               0           3                 13     ...       
2            43               0           2                  4     ...       
3            60               1           3                  3     ...       
4            28               1           1                  2     ...       

   time3  time4  car_valueA  car_valueB  car_valueC  car_valueD  car_valueE  \
0      1      0           0           0           0           0           0   
1      0      0           0           0           0           0           1   
2      1      0           0           0           1           0           0   
3      0      0           0           0           0           1           0   
4      0      1           0           0           0           1           0   

   car_valueF  car_valueG  car_valueH  
0           0           1           0  
1           0           0           0  
2           0           0           0  
3           0           0           0  
4           0           0           0  

[5 rows x 65 columns]

In [90]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

** Train and fit a logistic regression model on the training set.**

In [91]:
from sklearn.linear_model import LogisticRegression

In [92]:
logmodelA = LogisticRegression()
logmodelA.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

### Predictions and Evaluations

In [93]:
predA = logmodelA.predict(X_test)
predA

array([0, 1, 1, ..., 1, 0, 0], dtype=int64)

** Create a classification report for the model.**

In [94]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [95]:
print(classification_report(y_test,predA))
print('\n')
print(confusion_matrix(y_test,predA))
predA = logmodelA.score(X_train, y_train)
predA

             precision    recall  f1-score   support

          0       0.79      0.75      0.77      6477
          1       0.74      0.93      0.82     17850
          2       0.55      0.08      0.14      4776

avg / total       0.72      0.75      0.70     29103



[[ 4858  1569    50]
 [ 1045 16542   263]
 [  244  4156   376]]


0.74533914528907608

### Test 'B' alone

In [96]:
X = df[columns]
X.drop('A',axis=1,inplace=True)
X.drop('B',axis=1,inplace=True)
X.drop('C',axis=1,inplace=True)
X.drop('D',axis=1,inplace=True)
X.drop('E',axis=1,inplace=True)
X.drop('F',axis=1,inplace=True)
X.drop('G',axis=1,inplace=True)
y = df['B']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)
logmodelB = LogisticRegression()
logmodelB.fit(X_train,y_train)
predB = logmodelB.predict(X_test)
print(classification_report(y_test,predB))
print('\n')
print(confusion_matrix(y_test,predB))
predB = logmodelB.score(X_train, y_train)
predB

             precision    recall  f1-score   support

          0       0.62      0.68      0.65     15453
          1       0.59      0.52      0.56     13650

avg / total       0.61      0.61      0.60     29103



[[10529  4924]
 [ 6499  7151]]


0.60476246576149384

### Test 'C' alone

In [97]:
X = df[columns]
X.drop('A',axis=1,inplace=True)
X.drop('B',axis=1,inplace=True)
X.drop('C',axis=1,inplace=True)
X.drop('D',axis=1,inplace=True)
X.drop('E',axis=1,inplace=True)
X.drop('F',axis=1,inplace=True)
X.drop('G',axis=1,inplace=True)
y = df['C']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)
logmodelC = LogisticRegression()
logmodelC.fit(X_train,y_train)
predC = logmodelC.predict(X_test)
print(classification_report(y_test,predC))
print('\n')
print(confusion_matrix(y_test,predC))
predC = logmodelC.score(X_train, y_train)
predC

             precision    recall  f1-score   support

          1       0.66      0.80      0.72      8762
          2       0.65      0.16      0.25      6165
          3       0.63      0.89      0.73     11337
          4       0.81      0.30      0.44      2839

avg / total       0.66      0.65      0.60     29103



[[ 6975   237  1512    38]
 [ 2587   963  2586    29]
 [  896   268 10042   131]
 [   48    16  1926   849]]


0.64870556357317466

### Test 'D' alone

In [98]:
X = df[columns]
X.drop('A',axis=1,inplace=True)
X.drop('B',axis=1,inplace=True)
X.drop('C',axis=1,inplace=True)
X.drop('D',axis=1,inplace=True)
X.drop('E',axis=1,inplace=True)
X.drop('F',axis=1,inplace=True)
X.drop('G',axis=1,inplace=True)
y = df['D']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)
logmodelD = LogisticRegression()
logmodelD.fit(X_train,y_train)
predD = logmodelD.predict(X_test)
print(classification_report(y_test,predD))
print('\n')
print(confusion_matrix(y_test,predD))
predD = logmodelD.score(X_train, y_train)
predD

             precision    recall  f1-score   support

          1       0.50      0.29      0.37      3879
          2       0.43      0.20      0.27      6487
          3       0.73      0.93      0.82     18737

avg / total       0.63      0.68      0.64     29103



[[ 1143   929  1807]
 [  638  1307  4542]
 [  488   806 17443]]


0.69061644037345737

### Test 'E' alone

In [99]:
X = df[columns]
X.drop('A',axis=1,inplace=True)
X.drop('B',axis=1,inplace=True)
X.drop('C',axis=1,inplace=True)
X.drop('D',axis=1,inplace=True)
X.drop('E',axis=1,inplace=True)
X.drop('F',axis=1,inplace=True)
X.drop('G',axis=1,inplace=True)
y = df['E']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)
logmodelE = LogisticRegression()
logmodelE.fit(X_train,y_train)
predE = logmodelE.predict(X_test)
print(classification_report(y_test,predE))
print('\n')
print(confusion_matrix(y_test,predE))
predE = logmodelE.score(X_train, y_train)
predE

             precision    recall  f1-score   support

          0       0.72      0.71      0.72     15714
          1       0.67      0.67      0.67     13389

avg / total       0.69      0.69      0.69     29103



[[11220  4494]
 [ 4429  8960]]


0.69342915206314615

### Test 'F' alone

In [100]:
X = df[columns]
X.drop('A',axis=1,inplace=True)
X.drop('B',axis=1,inplace=True)
X.drop('C',axis=1,inplace=True)
X.drop('D',axis=1,inplace=True)
X.drop('E',axis=1,inplace=True)
X.drop('F',axis=1,inplace=True)
X.drop('G',axis=1,inplace=True)
y = df['F']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)
logmodelF = LogisticRegression()
logmodelF.fit(X_train,y_train)
predF = logmodelF.predict(X_test)
print(classification_report(y_test,predF))
print('\n')
print(confusion_matrix(y_test,predF))
predF = logmodelF.score(X_train, y_train)
predF

             precision    recall  f1-score   support

          0       0.86      0.89      0.88      9395
          1       0.54      0.30      0.39      7178
          2       0.57      0.81      0.67     10847
          3       1.00      0.00      0.00      1683

avg / total       0.68      0.66      0.63     29103



[[8374  275  746    0]
 [ 512 2163 4503    0]
 [ 708 1402 8737    0]
 [ 122  139 1421    1]]


0.66000058904956849

### Test 'G' alone

In [101]:
X = df[columns]
X.drop('A',axis=1,inplace=True)
X.drop('B',axis=1,inplace=True)
X.drop('C',axis=1,inplace=True)
X.drop('D',axis=1,inplace=True)
X.drop('E',axis=1,inplace=True)
X.drop('F',axis=1,inplace=True)
X.drop('G',axis=1,inplace=True)
y = df['G']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)
logmodelG = LogisticRegression()
logmodelG.fit(X_train,y_train)
predG = logmodelG.predict(X_test)
print(classification_report(y_test,predG))
print('\n')
print(confusion_matrix(y_test,predG))
predG = logmodelG.score(X_train, y_train)
predG

             precision    recall  f1-score   support

          1       0.53      0.41      0.46      6114
          2       0.56      0.80      0.66     11421
          3       0.72      0.64      0.68      9088
          4       0.42      0.01      0.01      2480

avg / total       0.59      0.60      0.57     29103



[[2499 3272  340    3]
 [1533 9091  787   10]
 [ 461 2808 5810    9]
 [ 224 1072 1168   16]]


0.60349600918917323

### Compare results

In [102]:
scores = pd.DataFrame({
    'Product': ['A','B','C','D','E','F','G'],
    'Score': [predA,predB,predC,predD,predE,predF,predE]})
scores.sort_values(by='Score', ascending=False)

Product     Score
0       A  0.745339
4       E  0.693429
6       G  0.693429
3       D  0.690616
5       F  0.660001
2       C  0.648706
1       B  0.604762

### Multiplying the accuracy together leaves an expected overall accuracy of 5.57%, which is significantly better than the random selection score of .04%.

In [103]:
overall = predA * predB * predC * predD * predE * predF * predG
overall

0.055775582775120951

### Test against the test data

In [110]:
test_data = pd.read_excel('test_v2_final.xlsx')
test_data.head()

shopping_pt  group_size  homeowner  car_age  risk_factor  age_oldest  \
0            1           1          0        9            5          24   
1            2           1          1        7            5          74   
2            2           1          0        4            4          26   
3            9           1          0       13            3          22   
4            2           1          0       11            5          27   

   age_youngest  married_couple  c_previous  duration_previous     ...      \
0            24               0           3                  9     ...       
1            74               0           2                 15     ...       
2            26               0           3                  1     ...       
3            22               0           1                  3     ...       
4            27               0           3                 12     ...       

   WI  WV  car_valueA  car_valueB  car_valueC  car_valueD  car_valueE  \
0   0   0           0           0           0           0           0   
1   0   0           0           0           0           0           0   
2   0   0           0           0           0           1           0   
3   0   0           0           0           0           0           0   
4   0   0           0           0           0           0           1   

   car_valueF  car_valueG  car_valueH  
0           1           0           0  
1           1           0           0  
2           0           0           0  
3           1           0           0  
4           0           0           0  

[5 rows x 65 columns]

In [141]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55716 entries, 0 to 55715
Data columns (total 65 columns):
shopping_pt          55716 non-null int64
group_size           55716 non-null int64
homeowner            55716 non-null int64
car_age              55716 non-null int64
risk_factor          55716 non-null int64
age_oldest           55716 non-null int64
age_youngest         55716 non-null int64
married_couple       55716 non-null int64
c_previous           55716 non-null int64
duration_previous    55716 non-null int64
first_insurance      55716 non-null int64
cost                 55716 non-null int64
Mon                  55716 non-null int64
Tues                 55716 non-null int64
Wed                  55716 non-null int64
Thur                 55716 non-null int64
Fri                  55716 non-null int64
Sat                  55716 non-null int64
time1                55716 non-null int64
time2                55716 non-null int64
time3                55716 non-null int64
time4    

In [142]:
#np.isnan(test_data).any()
test_resultsA = logmodelA.predict(test_data)
test_resultsB = logmodelB.predict(test_data)
test_resultsC = logmodelC.predict(test_data)
test_resultsD = logmodelD.predict(test_data)
test_resultsE = logmodelE.predict(test_data)
test_resultsF = logmodelF.predict(test_data)
test_resultsG = logmodelG.predict(test_data)

In [143]:
test_resultsA = pd.DataFrame(test_resultsA, columns=['A'])
pred_allA = test_resultsA.join(test_data)
test_resultsA.head()
pred_allA['A'].to_csv("Test_PredictionsA.csv")

In [144]:
test_resultsB = pd.DataFrame(test_resultsB, columns=['B'])
pred_allB = test_resultsB.join(test_data)
test_resultsB.head()
pred_allB['B'].to_csv("Test_PredictionsB.csv")

In [145]:
test_resultsC = pd.DataFrame(test_resultsC, columns=['C'])
pred_allC = test_resultsC.join(test_data)
test_resultsC.head()
pred_allC['C'].to_csv("Test_PredictionsC.csv")

In [146]:
test_resultsD = pd.DataFrame(test_resultsD, columns=['D'])
pred_allD = test_resultsD.join(test_data)
test_resultsD.head()
pred_allD['D'].to_csv("Test_PredictionsD.csv")

In [147]:
test_resultsE = pd.DataFrame(test_resultsE, columns=['E'])
pred_allE = test_resultsE.join(test_data)
test_resultsE.head()
pred_allE['E'].to_csv("Test_PredictionsE.csv")

In [148]:
test_resultsF = pd.DataFrame(test_resultsF, columns=['F'])
pred_allF = test_resultsF.join(test_data)
test_resultsF.head()
pred_allF['F'].to_csv("Test_PredictionsF.csv")

In [149]:
test_resultsG = pd.DataFrame(test_resultsG, columns=['G'])
pred_allG = test_resultsG.join(test_data)
test_resultsG.head()
pred_allG['G'].to_csv("Test_PredictionsG.csv")